steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
      ls -la
      
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.11'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      for dir in gcp-gke/terraform/uswest1-jonathan/cloudbuild/*
      do 
        cd ${dir}   
        env=${dir%*/}
        env=${env#*/}
        echo ""
        echo "*************** TERRAFORM INIT ******************"
        echo "******* At environment: ${env} ********"
        echo "*************************************************"
        terraform init || exit 1
        cd ../../../../../
      done
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.11'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      for dir in gcp-gke/terraform/uswest1-jonathan/cloudbuild/*
      do 
        cd ${dir}   
        env=${dir%*/}
        env=${env#*/}  
        echo ""
        echo "*************** TERRAFOM PLAN ******************"
        echo "******* At environment: ${env} ********"
        echo "*************************************************"
        terraform apply -auto-approve -lock=false || exit 1
        cd ../../../../../
      done
  timeout: '3600s'